### ISSUE TITLE
Multiple folders for different times of day synced with sunset and sunrise times like redshift

### ISSUE THREAD

**Issue by sallywoog** [vineetred/flowy#4]
Multiple folders for different times of day synced with sunset and sunrise times like redshift

Then we can have daytime folder and nightitme folders with light and dark wallpapers

Also synced with sunset and sunrise times like redshift/F.lux

**Comment by vineetred** [comment]
This sounds great! I'll definitely try implementing it.

**Comment by vineetred** [comment]
@sallywoog I've jotted down the logic that incorporates the sunset and sunrise times into my app. However, I'm still conflicted about having two different subfolders for light and dark wallpapers as I feel this is a very unelegant solution. I'll still push it so that those that want this feature can use it in the meantime. Do you have any other suggestions that can alleviate this?

**Comment by sallywoog** [comment]
how about a metadata file that "describes" the type of images rather than folders then they can be stored anywhere

**Comment by vineetred** [comment]
@sallywoog let me just make it clear. You want to have a metadata file that can tell the application what the kind of wallpaper it is -- if it is morning one or a dark one? Is this right?

**Comment by sallywoog** [comment]
You could, up to you, was just an idea

**Comment by vineetred** [comment]
Commit bfb15b1 adds this function. Check the README for steps on using it.
